repopick: fix UnicodeEncodingError while printing change subject
Commit 12189 had ⚡ in its message, which caused this

Applying change number 12189...
Traceback (most recent call last):
  File "/home/kronic/ten/vendor/aosip/build/tools/repopick.py", line 443, in <module>
    print(u'--> Subject:       "{0}"'.format(item['subject']))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u26a1' in position 52: ordinal not in range(128)

Change-Id: Ib5aff3472b25ce3f4d51710007bc0411c9df480b
Signed-off-by: Akhil Narang <me@akhilnarang.dev>